export const sessionsData = [
  {
    day: 'Monday',
    time: { startTime: '14:00:00', endTime: '15:00:00' },
    moduleName: 'Data Structures',
    moduleCode: 'CS102',
    sessionType: 'Lecture',
    coordinator: 'Prof. Johnson',
    location: 'Room 102',
    deliveryType: 'In-person',
  },
  {
    day: 'Monday',
    time: { startTime: '09:00:00', endTime: '10:00:00' },
    moduleName: 'Software Engineering',
    moduleCode: 'SE101',
    sessionType: 'Lecture',
    coordinator: 'Dr. Smith',
    location: 'Room 101',
    deliveryType: 'In-person',
  },
  {
    day: 'Monday',
    time: { startTime: '16:00:00', endTime: '18:00:00' },
    moduleName: 'Software',
    moduleCode: 'SE103',
    sessionType: 'Lecture',
    coordinator: 'Dr. Smith',
    location: 'Room 101',
    deliveryType: 'In-person',
  },
  {
    day: 'Tuesday',
    time: { startTime: '10:00', endTime: '11:30' },
    moduleName: 'Algorithms',
    moduleCode: 'CS103',
    sessionType: 'Lecture',
    coordinator: 'Dr. Davis',
    location: 'Room 103',
    deliveryType: 'Online',
  },
  {
    day: 'Tuesday',
    time: { startTime: '08:00', endTime: '10:00' },
    moduleName: 'Algorithms',
    moduleCode: 'CS103',
    sessionType: 'Lecture',
    coordinator: 'Dr. Davis',
    location: 'Room 103',
    deliveryType: 'Online',
  },
  {
    day: 'Tuesday',
    time: { startTime: '06:00', endTime: '07:00' },
    moduleName: 'Algorithms',
    moduleCode: 'CS103',
    sessionType: 'Lecture',
    coordinator: 'Dr. Davis',
    location: 'Room 103',
    deliveryType: 'Online',
  },
  {
    day: 'Wednesday',
    time: { startTime: '14:00', endTime: '15:30' },
    moduleName: 'Operating Systems',
    moduleCode: 'CS104',
    sessionType: 'Lecture',
    coordinator: 'Prof. Brown',
    location: 'Room 104',
    deliveryType: 'In-person',
  },
  {
    day: 'Thursday',
    time: { startTime: '13:00', endTime: '14:30' },
    moduleName: 'Databases',
    moduleCode: 'CS105',
    sessionType: 'Lecture',
    coordinator: 'Dr. Wilson',
    location: 'Room 105',
    deliveryType: 'In-person',
  },
  {
    day: 'Friday',
    time: { startTime: '08:00', endTime: '09:30' },
    moduleName: 'Networks',
    moduleCode: 'CS106',
    sessionType: 'Lecture',
    coordinator: 'Prof. Taylor',
    location: 'Room 106',
    deliveryType: 'Online',
  },
  {
    day: 'Saturday',
    time: { startTime: '10:00', endTime: '11:30' },
    moduleName: 'Software Testing',
    moduleCode: 'CS107',
    sessionType: 'Lab',
    coordinator: 'Dr. Lee',
    location: 'Room 107',
    deliveryType: 'In-person',
  },
  {
    day: 'Sunday',
    time: { startTime: '15:00', endTime: '16:30' },
    moduleName: 'Machine Learning',
    moduleCode: 'CS108',
    sessionType: 'Lecture',
    coordinator: 'Prof. White',
    location: 'Room 108',
    deliveryType: 'Online',
  },
];
