export const sessionsData = [
  {
    day: "Monday",
    time: { from: "09:00", to: "10:30" },
    moduleName: "Software Engineering",
    moduleCode: "SE101",
    sessionType: "Lecture",
    coordinator: "Dr. Smith",
    location: "Room 101",
    deliveryType: "In-person",
  },
  {
    day: "Monday",
    time: { from: "11:00", to: "12:30" },
    moduleName: "Data Structures",
    moduleCode: "CS102",
    sessionType: "Lecture",
    coordinator: "Prof. Johnson",
    location: "Room 102",
    deliveryType: "In-person",
  },
  {
    day: "Tuesday",
    time: { from: "10:00", to: "11:30" },
    moduleName: "Algorithms",
    moduleCode: "CS103",
    sessionType: "Lecture",
    coordinator: "Dr. Davis",
    location: "Room 103",
    deliveryType: "Online",
  },
  {
    day: "Wednesday",
    time: { from: "14:00", to: "15:30" },
    moduleName: "Operating Systems",
    moduleCode: "CS104",
    sessionType: "Lecture",
    coordinator: "Prof. Brown",
    location: "Room 104",
    deliveryType: "In-person",
  },
  {
    day: "Thursday",
    time: { from: "13:00", to: "14:30" },
    moduleName: "Databases",
    moduleCode: "CS105",
    sessionType: "Lecture",
    coordinator: "Dr. Wilson",
    location: "Room 105",
    deliveryType: "In-person",
  },
  {
    day: "Friday",
    time: { from: "08:00", to: "09:30" },
    moduleName: "Networks",
    moduleCode: "CS106",
    sessionType: "Lecture",
    coordinator: "Prof. Taylor",
    location: "Room 106",
    deliveryType: "Online",
  },
  {
    day: "Saturday",
    time: { from: "10:00", to: "11:30" },
    moduleName: "Software Testing",
    moduleCode: "CS107",
    sessionType: "Lab",
    coordinator: "Dr. Lee",
    location: "Room 107",
    deliveryType: "In-person",
  },
  {
    day: "Sunday",
    time: { from: "15:00", to: "16:30" },
    moduleName: "Machine Learning",
    moduleCode: "CS108",
    sessionType: "Lecture",
    coordinator: "Prof. White",
    location: "Room 108",
    deliveryType: "Online",
  },
];
